import '@/styles/globals.css'
import Head from 'next/head'
import Cookies from 'js-cookie'
import { useEffect } from 'react'

export default function App ({ Component, pageProps }) {
  useEffect(() => {
    Cookies.set('message', 'hello world')
  })

  return (
    <>
      <Head>
        <title>web-challenge-laksito</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Component {...pageProps} />
    </>
  )
}
